spring:
  application:
    name: payment-service
  jpa:
    show-sql: true
    properties:
      format-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ecommerce.events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8083

logging:
  level:
    com.ecommerce.order: debug
    org.springframework.web: info

payment:
  executor:
    pool-size: 10  # Number of concurrent payment processing threads
  gateway:
    timeout-seconds: 10
    success-rate-percent: 100